package com.wasalska.demo.dataloading.service;

import org.springframework.stereotype.Component;

@Component("sensorMockService")
public class SensorMockService extends SensorService{
    @Override
    protected String getSensorsJson(int stationId) {
        return "{\"@context\":{\"meta\":\"https://schema.org/meta\",\"totalPages\":\"https://schema.org/totalPages\",\"links\":\"https://schema.org/links\"},\"@context\":{\"Lista stanowisk pomiarowych dla podanej stacji\":{\"@id\":\"https://api.gios.gov.pl/pjp-api/v1/rest/station/sensors\"},\"links\":\"https://schema.org/relatedLink\",\"totalPages\":\"https://schema.org/numberOfPages\"},\"Lista stanowisk pomiarowych dla podanej stacji\":[{\"Identyfikator stanowiska\":32740,\"Identyfikator stacji\":20647,\"Wskaźnik\":\"pył zawieszony PM10\",\"Wskaźnik - wzór\":\"PM10\",\"Wskaźnik - kod\":\"PM10\",\"Id wskaźnika\":3},{\"Identyfikator stanowiska\":32741,\"Identyfikator stacji\":20647,\"Wskaźnik\":\"pył zawieszony PM2.5\",\"Wskaźnik - wzór\":\"PM2.5\",\"Wskaźnik - kod\":\"PM2.5\",\"Id wskaźnika\":69},{\"Identyfikator stanowiska\":32742,\"Identyfikator stacji\":20647,\"Wskaźnik\":\"pył zawieszony PM10\",\"Wskaźnik - wzór\":\"PM10\",\"Wskaźnik - kod\":\"PM10\",\"Id wskaźnika\":3},{\"Identyfikator stanowiska\":32743,\"Identyfikator stacji\":20647,\"Wskaźnik\":\"benzo(a)piren w PM10\",\"Wskaźnik - wzór\":\"BaP(PM10)\",\"Wskaźnik - kod\":\"BaP(PM10)\",\"Id wskaźnika\":61}],\"meta\":{\"dc:description\":\"Usługa sieciowa udostępniająca listę funkcjonujących stanowisk pomiarowych\",\"sy:updateFrequency\":\"1\",\"dc:language\":\"pol (ISO 639-2 / ISO 639-3)\",\"schema:contentType\":\"application/ld+json\",\"schema:provider\":{\"@context\":\"https://schema.org\",\"@type\":\"Organization\",\"address\":{\"@type\":\"PostalAddress\",\"addressLocality\":\"Warszawa\",\"postalCode\":\"02-362\",\"streetAddress\":\"Bitwy Warszawskiej 1920 3\"},\"email\":\"api@gios.gov.pl\",\"name\":\"Główny Inspektorat Ochrony Środowiska\"},\"schema:dateModified\":\"03.11.2022\",\"dc:title\":\"Lista stanowisk pomiarowych na stacji\",\"schema:datePublished\":\"10.04.2017\",\"schema:keywords\":\"powietrze, jakość powietrza, zanieczyszczenie powietrza, stacje pomiarowe, stanowiska pomiarowe, monitoring powietrza, Państwowy Monitoring Środowiska, środowisko, stan środowiska\",\"sy:updatePeriod\":\"year\",\"schema:isPartOf\":\"Państwowy Monitoring Środowiska, Jakość powietrza\"},\"links\":{\"next\":\"https://api.gios.gov.pl/pjp-api/v1/rest/station/sensors/20647?page=1&size=20\",\"last\":\"https://api.gios.gov.pl/pjp-api/v1/rest/station/sensors/20647?page=0&size=20\",\"prev\":\"https://api.gios.gov.pl/pjp-api/v1/rest/station/sensors/20647?page=0&size=20\",\"self\":\"https://api.gios.gov.pl/pjp-api/v1/rest/station/sensors/20647?page=0&size=20\",\"first\":\"https://api.gios.gov.pl/pjp-api/v1/rest/station/sensors/20647?page=0&size=20\"},\"totalPages\":1}";
    }
}
